services:
  globaldb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: global-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-global:/var/opt/mssql
    
  africadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: africa-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - mssql-africa:/var/opt/mssql
  
  asiadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: asia-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    volumes:
      - mssql-asia:/var/opt/mssql
  
  europedb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: europe-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1436:1433"
    volumes:
      - mssql-europe:/var/opt/mssql
  
  northamericadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: northamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1437:1433"
    volumes:
      - mssql-asia:/var/opt/mssql
  
  southamericadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: southamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1438:1433"
    volumes:
      - mssql-southamerica:/var/opt/mssql
  
  oceaniadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: oceania-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1439:1433"
    volumes:
      - mssql-oceania:/var/opt/mssql
  
  antarcticadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: antarctica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1440:1433"
    volumes:
      - mssql-antarctica:/var/opt/mssql
  
  
  
  article-service:
    build:
      context: .
      dockerfile: ArticleService/Dockerfile
    depends_on:
      - globaldb
      - africadb
      - asiadb
      - europedb
      - northamericadb
      - southamericadb
      - oceaniadb
      - antarcticadb
    deploy:
      replicas: 3

volumes:
  mssql-global:
  mssql-africa:
  mssql-asia:
  mssql-europe:
  mssql-northamerica:
  mssql-southamerica:
  mssql-oceania:
  mssql-antarctica: