networks:
  HHL:
    driver: overlay

volumes:
  mssql-global:
  mssql-africa:
  mssql-asia:
  mssql-europe:
  mssql-northamerica:
  mssql-southamerica:
  mssql-oceania:
  mssql-antarctica:
  mssql-profanity:
  mssql-comment:
  mssql-draft:
  mssql-subscriber:
  rps_seq_data:
  zipkin_data:

services:
  # Databases
  global-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-global:/var/opt/mssql

  africa-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - mssql-africa:/var/opt/mssql

  asia-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    volumes:
      - mssql-asia:/var/opt/mssql

  europe-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1436:1433"
    volumes:
      - mssql-europe:/var/opt/mssql

  northamerica-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1437:1433"
    volumes:
      - mssql-northamerica:/var/opt/mssql

  southamerica-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1438:1433"
    volumes:
      - mssql-southamerica:/var/opt/mssql

  oceania-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1439:1433"
    volumes:
      - mssql-oceania:/var/opt/mssql

  antarctica-article-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1440:1433"
    volumes:
      - mssql-antarctica:/var/opt/mssql

  profanity-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1441:1433"
    volumes:
      - mssql-profanity:/var/opt/mssql

  comment-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1442:1433"
    volumes:
      - mssql-comment:/var/opt/mssql

  draft-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1443:1433"
    volumes:
      - mssql-draft:/var/opt/mssql
        
  subscriber-db:
    networks:
      - HHL
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1444:1433"
    volumes:
      - mssql-subscriber:/var/opt/mssql

  #Services
  profanity-service:
    networks:
      - HHL
    image: profanity-service:latest
    ports:
      - "8003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Profanity=Server=profanity-db,1433;Database=Profanity;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;

  comment-service:
    networks:
      - HHL
    image: comment-service:latest
    ports:
      - "8004:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Comment=Server=comment-db,1433;Database=Comment;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;

  draft-service:
    networks:
      - HHL
    image: draft-service:latest
    ports:
      - "8005:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Draft=Server=draft-db,1433;Database=Draft;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;

  publisher-service:
    networks:
      - HHL
    image: publisher-service:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8006:80"  
      
  newsletter-service:
    networks:
      - HHL
    image: newsletter-service:latest
    environment:
      - ASPNETCORE_URLS=http://+:80

  monitoring-service:
    networks:
      - HHL
    image: monitoring-service:latest
    ports:
      - "8085:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
        
  subscriber-service:
    networks:
      - HHL
    image: subscriber-service:latest
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Subscriber=Server=subscriber-db,1433;Database=Subscriber;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
    ports:
      - "8007:80"
    depends_on:
      - subscriber-db
      - seq
      - zipkin

  article-service:
    networks:
      - HHL
    image: article-service:latest
    deploy:
      replicas: 3
      endpoint_mode: vip
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Global=Server=global-article-db,1433;Database=GlobalDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Africa=Server=africa-article-db,1433;Database=AfricaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Asia=Server=asia-article-db,1433;Database=AsiaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Europe=Server=europe-article-db,1433;Database=EuropeDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__NorthAmerica=Server=northamerica-article-db,1433;Database=NorthAmericaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__SouthAmerica=Server=southamerica-article-db,1433;Database=SouthAmericaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Oceania=Server=oceania-article-db,1433;Database=OceaniaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Antarctica=Server=antarctica-article-db,1433;Database=AntarcticaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;

  seq:
    networks:
      - HHL
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  zipkin:
    networks:
      - HHL
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin

  zipkin-storage:
    networks:
      - HHL
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    volumes:
      - zipkin_data:/mysql/data

  rabbitmq:
    networks:
      - HHL
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    networks:
      - HHL
    image: redis:7
    ports:
      - "6379:6379"
