services:
  # Global DB
  global-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: global-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-global:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # Africa DB
  africa-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: africa-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - mssql-africa:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # Asia DB
  asia-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: asia-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    volumes:
      - mssql-asia:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # Europe DB
  europe-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: europe-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1436:1433"
    volumes:
      - mssql-europe:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # North America DB
  northamerica-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: northamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1437:1433"
    volumes:
      - mssql-northamerica:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # South America DB
  southamerica-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: southamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1438:1433"
    volumes:
      - mssql-southamerica:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # Oceania DB
  oceania-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: oceania-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1439:1433"
    volumes:
      - mssql-oceania:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  # Antarctica DB
  antarctica-article-db:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: antarctica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1440:1433"
    volumes:
      - mssql-antarctica:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  profanitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: profanity-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1441:1433"
    volumes:
      - mssql-profanity:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  commentdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: comment-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1442:1433"
    volumes:
      - mssql-comment:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  draftdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: draft-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1443:1433"
    volumes:
      - mssql-draft:/var/opt/mssql
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -U SA -P Pazzw0rd2025 -Q 'SELECT 1'" ]
      interval: 5s
      retries: 10
      start_period: 10s
  
  profanity-service:
    build:
      context: .
      dockerfile: ProfanityService/Dockerfile
    depends_on:
        profanitydb:
          condition: service_healthy
    ports:
      - 8003:80
    environment: 
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Profanity=Server=profanity-db,1433;Database=Profanity;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
  
  comment-service:
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    depends_on:
        commentdb:
          condition: service_healthy
    ports:
      - 8004:80
    environment: 
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Comment=Server=comment-db,1433;Database=Comment;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
  
  draft-service:
    build:
      context: .
      dockerfile: DraftService/Dockerfile
    depends_on:
      draftdb:
        condition: service_healthy
    ports:
      - 8005:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Draft=Server=draft-db,1433;Database=Draft;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
  
  
  article-service:
    build:
      context: .
      dockerfile: ArticleService/Dockerfile
    depends_on:
        global-article-db:
          condition: service_healthy
        africa-article-db:
          condition: service_healthy
        asia-article-db:
          condition: service_healthy
        europe-article-db:
          condition: service_healthy
        northamerica-article-db:
          condition: service_healthy
        southamerica-article-db:
          condition: service_healthy
        oceania-article-db:
          condition: service_healthy
        antarctica-article-db:
          condition: service_healthy
    deploy:
      replicas: 3
    ports:
      - "8000-8002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Global=Server=global-article-db,1433;Database=GlobalDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Africa=Server=africa-article-db,1433;Database=AfricaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Asia=Server=asia-article-db,1433;Database=AsiaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Europe=Server=europe-article-db,1433;Database=EuropeDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__NorthAmerica=Server=northamerica-article-db,1433;Database=NorthAmericaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__SouthAmerica=Server=southamerica-article-db,1433;Database=SouthAmericaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Oceania=Server=oceania-article-db,1433;Database=OceaniaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
      - ConnectionStrings__Antarctica=Server=antarctica-article-db,1433;Database=AntarcticaDb;User Id=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;
  
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    volumes:
      - rps_seq_data:/data
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
  
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=zipkin-storage
      - MYSQL_USER=zipkin
      - MYSQL_PASS=zipkin
    depends_on:
      - zipkin-storage
  
  zipkin-storage:
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    volumes:
      - zipkin_data:/mysql/data
    

volumes:
  mssql-global:
  mssql-africa:
  mssql-asia:
  mssql-europe:
  mssql-northamerica:
  mssql-southamerica:
  mssql-oceania:
  mssql-antarctica:
  mssql-profanity:
  mssql-comment:
  mssql-draft:
  rps_seq_data:
  zipkin_data: