services:
  globaldb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: global-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - mssql-global:/var/opt/mssql
    
  africadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: africa-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - mssql-africa:/var/opt/mssql
  
  asiadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: asia-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1435:1433"
    volumes:
      - mssql-asia:/var/opt/mssql
  
  europedb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: europe-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1436:1433"
    volumes:
      - mssql-europe:/var/opt/mssql
  
  northamericadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: northamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1437:1433"
    volumes:
      - mssql-northamerica:/var/opt/mssql
  
  southamericadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: southamerica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1438:1433"
    volumes:
      - mssql-southamerica:/var/opt/mssql
  
  oceaniadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: oceania-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1439:1433"
    volumes:
      - mssql-oceania:/var/opt/mssql
  
  antarcticadb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: antarctica-article-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1440:1433"
    volumes:
      - mssql-antarctica:/var/opt/mssql
  
  profanitydb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: profanity-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      PROFANITY_DB_CONSTR: "Server=profanity-db,1441;Database=AntarcticaDb;Initial Catalog=Profanity;User ID=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;"
    ports:
      - "1441:1433"
    volumes:
      - mssql-profanity:/var/opt/mssql
  
  commentdb:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    container_name: comment-db
    environment:
      SA_PASSWORD: "Pazzw0rd2025"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
      COMMENT_DB_CONSTR: "Server=comment-db,1442;Database=AntarcticaDb;Initial Catalog=Profanity;User ID=SA;Password=Pazzw0rd2025;TrustServerCertificate=True;"
    
    ports:
      - "1442:1433"
    volumes:
      - mssql-comment:/var/opt/mssql
  
  profanity-service:
    build:
      context: .
      dockerfile: ProfanityService/Dockerfile
    depends_on:
      - profanitydb
    ports:
      - 8003:80
  
  comment-service:
    build:
      context: .
      dockerfile: CommentService/Dockerfile
    depends_on:
      - commentdb
    ports:
      - 8004:80
  
  
  article-service:
    build:
      context: .
      dockerfile: ArticleService/Dockerfile
    depends_on:
      - globaldb
      - africadb
      - asiadb
      - europedb
      - northamericadb
      - southamericadb
      - oceaniadb
      - antarcticadb
    deploy:
      replicas: 3
    ports:
      - "8000-8002:80"

volumes:
  mssql-global:
  mssql-africa:
  mssql-asia:
  mssql-europe:
  mssql-northamerica:
  mssql-southamerica:
  mssql-oceania:
  mssql-antarctica:
  mssql-profanity:
  mssql-comment: